### ISSUE TITLE
[Goal] Add LDP support.

### ISSUE THREAD

**Issue by deiu** [deiu/rww.io#1]
http://www.w3.org/TR/2013/WD-ldp-20130730/

**Comment by olberger** [comment]
You may find in https://github.com/olberger/rww.io/commit/4610a35f346a68e32f20445e66f156c5bd3104c1 the start of a paging mechanism for directory contents listing ala LDP.

**Comment by deiu** [comment]
I've merged it in 123fb0934f4bc6c5242c7e9b5d28f0ccedd380e8.

All LDP related code can now be found in the LDP branch. I'm leaving this issue open until full support is added.

**Comment by deiu** [comment]
Implemented in https://github.com/deiu/rww.io/releases/tag/v.1.2 :-)
