### ISSUE TITLE
Create WebID on mobile device

### ISSUE THREAD

**Issue by shouben** [deiu/rww.io#16]
It's not possible for me to create a WebID (on account.rww.io, databox or other) on Iphone/tablet/android mobile device.

Do mobile browsers support the creation of the certificates?
Or is there an other issue (an error on the client) when I click on 'check' after filling in the account details?

**Comment by deiu** [comment]
Hi,

I just tried and it worked for me in Chrome on Android. Can you please provide more details, such as browser version, OS version, any error messages, etc.?

**Comment by shouben** [comment]
Andrei,

Sorry, I used IOS 7.1 on a IPhone.

Sonja

Verstuurd vanaf mijn iPhone

**Comment by akuckartz** [comment]
Do we know what happens on a current iOS version?

**Comment by shouben** [comment]
Dear Andreas/Andrei,

I'll try to describe it and if needed I'll mail you a video where you can
see what happens and/or debug info:

issue: can't create a WebID
on: Iphone 5 / IOS 7
via: linkeddata.github.io/signup

I can enter the user credentials (at signup for a WebID/storage)

after clicking on 'Check'
- the page flickers
- but nothing happens

Nothings seems to be loaded
The only options I have, are: help/clear

Does this help or do you need additional info (I can't debug my phone from
here, this is possible this weekend when I'm back home)

Regards,
Sonja

S. Houben

connecting your digital world

z-koo.com
s.houben@z-koo.com
+31 (0)6 37 45 57 51

2015-06-11 6:03 GMT+02:00 Andreas Kuckartz notifications@github.com:

**Comment by melvincarvalho** [comment]
Here's a video of a webid certificate created on IOS

https://www.youtube.com/watch?v=4MF6DpZmvrI

**Comment by shouben** [comment]
Dear Andrei/Andreas,

Did you receive the input of 11th June or do you need more info:

Dear Andreas/Andrei,

I'll try to describe it and if needed I'll mail you a video where you can
see what happens and/or debug info:

issue: can't create a WebID
on: Iphone 5 / IOS 7
via: linkeddata.github.io/signup

I can enter the user credentials (at signup for a WebID/storage)

after clicking on 'Check'
- the page flickers
- but nothing happens

Nothings seems to be loaded
The only options I have, are: help/clear

Does this help or do you need additional info (I can't debug my phone from
here, this is possible this weekend when I'm back home)

Regards,
Sonja

S. Houben

connecting your digital world

z-koo.com
s.houben@z-koo.com
+31 (0)6 37 45 57 51

2015-06-11 9:47 GMT+02:00 sonja houben houbensg@gmail.com:

**Comment by akuckartz** [comment]
@shouben I can not help here. But in my opinion supporting IOS 7 should not be a high priority for this project. The current version is 8.3. Can you upgrade and try again?

**Comment by shouben** [comment]
Hello Andreas,

No problem, I can upgrade to 8.3. Do you know if it's possible to create a webID with IOS (8.3)?

Regards,
Sonja

Verstuurd vanaf mijn iPhone

**Comment by shouben** [comment]
Sorry Andrei/Andreas

Verstuurd vanaf mijn iPhone

**Comment by shouben** [comment]
Andreas/Andrei
upgrading to IOS 8.3 is not solving the issue: creating a webid on mobile device: IOS/8.3 (latest version).
On Iphone/IOS 8.3 via
   linkeddata.github.io signup
   I did signup for a webid 
   I receive the message that webid signud is a Success
      note: the last step (see image below) ' Updating preferences file is not marked as successfull 
     (I don't know if this is relevant) 

Unfortunately I can't loging with the created webid 
  on Iphone/IOS 8.3 via
  linkeddata.github.io login

![img_0841](https://cloud.githubusercontent.com/assets/873352/8235157/93868e0c-15e0-11e5-9ecc-5a4df52112db.PNG)
![img_0840](https://cloud.githubusercontent.com/assets/873352/8235158/9387599a-15e0-11e5-852d-82b58cd7505a.PNG)

If you need you need more information, please let me know.

Sonja

**Comment by akuckartz** [comment]
@shouben Why did you close this issue ?!

**Comment by shouben** [comment]
No, because it's still open!
Would you like me to close it an report it otherwise?

Verstuurd vanaf mijn iPhone
