### ISSUE TITLE
Adding data through SPARQL query doesn't seem to work

### ISSUE THREAD

**Issue by lmatteis** [deiu/rww.io#5]
How do I add triples programmatically? This doesn't seem to work:

```
curl -d 'INSERT DATA \
{ <test> \
         <http://xmlns.com/foaf/0.1/age> 66 }' \
-H Content-type:*/sparql-query \
http://luca.rww.io/foo
```

**Comment by melvincarvalho** [comment]
Try

```
curl -d 'INSERT DATA { <test> <http://xmlns.com/foaf/0.1/age> 66 . }' -H Content-type:application/sparql-update http://luca.rww.io/foo
```

**Comment by lmatteis** [comment]
Getting `Construct Template not found`. Doesn't seem to be adding data. For some reason now my other data appears... not sure what's going on.

**Comment by melvincarvalho** [comment]
Try it without the \ inside the sparql query ...

**Comment by lmatteis** [comment]
ah you're right! Weird, how do you "new line" in bash? Thanks it works now!
