### ISSUE TITLE
curl example?

### ISSUE THREAD

**Issue by ericdscott** [deiu/rww.io#6]
Thanks for making this available.

I would benefit from an example in your 'help' of a complete curl statement querying the contents of the repo. e.g "Select  \* Where {?s ?p ?o} limit 10" 

Thanks!

**Comment by deiu** [comment]
All you have to do is pass your SPARQL query as an urlencoded string to the document you want to get data from.

Say you have a document at http://example.rww.io/test, then you add ?query=<urlencoded SPARQL>, so it becomes:

http://example.rww.io/test?query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D%20LIMIT%2010

**Comment by ericdscott** [comment]
Thanks for your reply.

When I do that, I get an error:

HTTP failed unusually (no handler set) (cross-site violation? no net?) 
for http://...
Unhandled content type: application/json, readyState =4

Also it's not clear to me how I could pose queries from a shell command. 
It's my understanding that curl is the proper tool, but I'm not clear on 
how the webID authentication and header specifications fit into the 
picture. All of my naive attempts after reading the man for curl give me 
errors, so if you could provide me with a working example of a curl 
statement that touches the points in your existing help for a request 
method, response type and media type, I would greatly appreciate it.

Thanks again,

**Comment by deiu** [comment]
It works perfectly here. I don't understand where your error comes from. Do you have a link for the resource you are trying to query? Also, do you want to use curl for testing or for production?

WebID authentication is useful for accessing protected resources. This also means that you will have to add the certificate to the request. This is how you'd normally do it:

`curl --cert certificate.pem:test http://example.rww.io/test?query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D%20LIMIT%2010`

There is no SPARQL endpoint that covers all your data on RWW.IO. Each resource (document) is a SPARQL endpoint by itself. To this matter, please note that RWW.IO returns JSON by default for SPARQL selects. You cannot currently request a different content type, as this is a friendly way of getting information back (vs the alternative of returning plain text that you have to parse yourself).

If you would like to add data into a document, you could use the following curl example:

`curl -d 'INSERT DATA { <a> <b> <c> . }' -H "Content-Type: application/sparql-update" http://example.rww.io/test`

**Comment by ericdscott** [comment]
When I enter this:

curl --cert webid.pem 
http://ericscott.rww.io/jk?query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D%20LIMIT%2010

Where 'webid.pem' is the pem I've associated with my webID, which seems 
to work fine when I log in to your website. (Actually I used the p12 
version which I'm led to believe is required by Firefox).

The response is

...

<div class="clear center error">Access to the requested URI is denied or 
it does not exist.</div>

...

There is no password associated with the pem file to my knowledge. I 
tried the p12 file with password and got the same result.

To answer your question, at this point I'm just playing around for now 
to see if I can access the contents of a small file called 'jk' I put up 
this morning.

I appreciate your help.

**Comment by ericdscott** [comment]
Ah I see the problem: I forgot the use https, and curl will throw an 
error if I don't use a -k argument.

  This works:

curl -k --cert  webid.pem 
https://ericscott.rww.io/jk?query=SELECT%20*%20WHERE%20%7B%3Fs%20%3Fp%20%3Fo%7D%20LIMIT%2010

I think I'm good now. Thanks again!

Just a bit of feedback, you might want to include a few more examples so 
that we newbies to raw http can find our feet more easily. Otherwise 
this looks like a great resource!

Cheers,

**Comment by deiu** [comment]
Yes, you are right. I will try to add more examples soon, though RWW.IO isn't really a service for beginners. :)
